apiVersion: apps/v1
kind: Deployment
metadata:
  name: cars-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: rest-server
  template:
    metadata:
      name: cars-rest-client-pod
      labels:
        component: rest-server
    spec:
      containers:
        - name: cars-rest-server
          image: learningmw1991/restapi_cars:02
          ports:
            - containerPort: 5000
              protocol: TCP
              name: cars-rest-srv