apiVersion: apps/v1
kind: Deployment
metadata:
  name: cars-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: cars-rest
  template:
    metadata:
      name: cars-rest-client-pod
      labels:
        component: cars-rest
    spec:
      containers:
        - name: cars-rest-server
          image: learningmw1991/restapi_cars:02
          ports:
            - containerPort: 5000
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: cars-rest-service
spec:
  selector:
    component: cars-rest
  ports:
  - name: cars-rest-port
    protocol: TCP
    port: 5001
    targetPort: 5000