apiVersion: apps/v1
kind: Deployment
metadata:
  name: foods-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: rest-server
  template:
    metadata:
      name: foods-rest-client-pod
      labels:
        component: rest-server
    spec:
      containers:
        - name: foods-rest-server
          image: learningmw1991/restapi_foods:02
          ports:
            - containerPort: 5000
              protocol: TCP
              name: foods-rest-srv