apiVersion: apps/v1
kind: Deployment
metadata:
  name: foods-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: foods-rest
  template:
    metadata:
      name: foods-rest-client-pod
      labels:
        component: foods-rest
    spec:
      containers:
        - name: foods-rest-server
          image: learningmw1991/restapi_foods:02
          ports:
            - containerPort: 5000
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: foods-rest-service
spec:
  selector:
    component: foods-rest
  ports:
  - name: cars-rest-port
    protocol: TCP
    port: 5002
    targetPort: 5000