apiVersion: v1
kind: Service
metadata:
  name: cars-rest-nod-port
spec:
  type: NodePort
  selector:
    component: rest-server
  ports:
    - port: 3000
      targetPort: cars-rest-srv
      nodePort: 30001
      name: cars-rest-svc
    - port: 3001
      targetPort: foods-rest-srv
      nodePort: 30002
      name: foods-rest-svc