apiVersion: v1
kind: Service
metadata:
  name: cars-rest-nod-port
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5001
      nodePort: 30001
      protocol: TCP
  selector:
    component: cars-rest